name = "RadCalNet"
uuid = "573d4978-4615-42ee-907a-4f7d0c4f09b5"
authors = ["Walter Dal'Maz Silva"]
version = "1.0.0-DEV"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
